apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-local
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          imagePullPolicy: IfNotPresent
          image: spring-docker-local:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring
  name: spring-docker-local
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring
  type: ClusterIP