kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""